"""Add roles_permissions table

Revision ID: 49b618d3c7ea
Revises: aaf2d5b70e1b
Create Date: 2026-03-14 12:56:45.572655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49b618d3c7ea'
down_revision: Union[str, Sequence[str], None] = 'aaf2d5b70e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('level_access', postgresql.ENUM('FORBIDDEN', 'READ', 'READ_BRANCH', 'FULL', 'FULL_BRANCH', name='access_level'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_permissions_id'), 'roles_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_permissions_id'), table_name='roles_permissions')
    op.drop_table('roles_permissions')
    # ### end Alembic commands ###
