"""Add level_access column to roles_permissions

Revision ID: 850e78404067
Revises: 0e2397c1f7eb
Create Date: 2026-03-14 11:50:14.490929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.consts.access import AccessLevel

# revision identifiers, used by Alembic.
revision: str = '850e78404067'
down_revision: Union[str, Sequence[str], None] = '0e2397c1f7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_access_level_enum() -> postgresql.ENUM:
    return postgresql.ENUM(*[val for val in dir(AccessLevel) if not val.startswith("__") and val.isupper()], name="access_level")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    levels = _get_access_level_enum()
    levels.create(op.get_bind())
    op.add_column('roles_permissions', sa.Column('level_access', levels, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles_permissions', 'level_access')
    levels = _get_access_level_enum()
    levels.drop(op.get_bind())
    # ### end Alembic commands ###
